version: "3"

services:
  redis:
    image: 'redis:latest'

  api:
    image: mymcuu.id/api:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - CORS=https://mymcuu.id
    ports:
      - 3985:8080